# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(max_length=150)),
                ('Event_date', models.DateField(blank=True, null=True)),
                ('Location', models.CharField(max_length=150)),
                ('Event_type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('idcard_img', models.ImageField(blank=True, default=1, null=True, upload_to='')),
                ('ticket_count', models.IntegerField(null=True)),
                ('reg_type', models.CharField(choices=[('SF', 'Self'), ('GRP', 'Group'), ('CRP', 'Corporate'), ('Other', 'Other')], default='SF', max_length=10)),
                ('Event', models.CharField(max_length=50)),
            ],
        ),
    ]
