# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_auto_20170430_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='regnum',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='Event_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='Event_type',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='reg_type',
            field=models.CharField(choices=[('SF', 'Self'), ('GRP', 'Group'), ('CRP', 'Corporate'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='ticket_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
