# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_auto_20170501_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
